# Generated by Django 4.1.3 on 2023-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
